### ISSUE TITLE
Choose/create a language

### ISSUE THREAD

**Issue by Jacquwes** [Cumteam/Cumpilator#1]

**Comment by Mideky-hub** [comment]
On peut soit refaire un compilateur C, partant de bas-niveau et remontant jusque le résultat final.

Soit on peut faire un nouveau langage.

Je préfère refaire le C, c'est plus intéressant je trouve ^^'

**Comment by Mideky-hub** [comment]
Je suis d'accord. Je vais préparer un document pour répartir les tâches et la gestion du projet.
